"""
Sample Meroitic inscription data based on published REM (Répertoire d'Épigraphie Méroïtique)
transliterations. These are well-known inscriptions from scholarly literature.

Sources: Griffith 1911, Hintze 1979, Rilly 2007, Rilly & de Voogt 2012.

Transliteration conventions follow the standard REM notation.
"""

# Known Meroitic vocabulary with scholarly consensus translations
KNOWN_VOCABULARY = {
    # Royal/political titles
    "qore": {"translation": "ruler/king", "category": "title", "source": "royal inscriptions"},
    "kdke": {"translation": "queen mother (Candace)", "category": "title", "source": "royal inscriptions"},
    "ktke": {"translation": "queen mother (variant)", "category": "title", "source": "royal inscriptions"},
    "pqr": {"translation": "deputy/viceroy", "category": "title", "source": "administrative texts"},
    "pelmos": {"translation": "strategos/general", "category": "title", "source": "Rilly 2007"},
    "peseto": {"translation": "viceroy of Akine", "category": "title", "source": "administrative"},
    "beleqe": {"translation": "chief", "category": "title", "source": "Rilly 2007"},
    "arike": {"translation": "prince", "category": "title", "source": "Rilly 2007"},

    # Religious terms
    "mk": {"translation": "god", "category": "religion", "source": "temple inscriptions"},
    "amni": {"translation": "Amun (deity)", "category": "religion", "source": "theophoric names"},
    "apedmk": {"translation": "Apedemak (lion god)", "category": "religion", "source": "temple inscriptions"},
    "wos": {"translation": "Isis (deity)", "category": "religion", "source": "funerary formula"},
    "mhe": {"translation": "Mash (sun god)", "category": "religion", "source": "Rilly 2007"},
    "mnp": {"translation": "Mandulis (deity)", "category": "religion", "source": "temple texts"},
    "sebke": {"translation": "Sebiumeker (deity)", "category": "religion", "source": "temple texts"},

    # Funerary/offering terms
    "ate": {"translation": "bread/food offering", "category": "funerary", "source": "offering tables"},
    "yi": {"translation": "water/drink", "category": "funerary", "source": "offering tables"},
    "pesto": {"translation": "to give", "category": "funerary", "source": "offering formula"},
    "plote": {"translation": "to pour (libation)", "category": "funerary", "source": "Rilly 2007"},
    "beke": {"translation": "to beget/produce", "category": "funerary", "source": "genealogies"},

    # Kinship/person terms
    "abr": {"translation": "man", "category": "person", "source": "funerary texts"},
    "kdi": {"translation": "woman", "category": "person", "source": "funerary texts"},
    "lh": {"translation": "son/child", "category": "kinship", "source": "genealogies"},
    "sr": {"translation": "sister/daughter", "category": "kinship", "source": "Rilly 2007"},

    # Adjectives/descriptors
    "mlo": {"translation": "good/beautiful", "category": "adjective", "source": "epithets"},
    "qo": {"translation": "great/big", "category": "adjective", "source": "royal epithets"},
    "selele": {"translation": "protection", "category": "noun", "source": "religious texts"},

    # Geographic terms
    "tenke": {"translation": "west/western", "category": "geography", "source": "directional"},
    "tedke": {"translation": "east/eastern", "category": "geography", "source": "directional"},
    "akine": {"translation": "Akine (province)", "category": "geography", "source": "administrative"},
    "to": {"translation": "land/territory", "category": "geography", "source": "Rilly 2007"},

    # Numbers (tentative)
    "ar": {"translation": "one (tentative)", "category": "number", "source": "Rilly 2007"},
}

# Known grammatical morphemes
KNOWN_MORPHEMES = {
    # Suffixes
    "-l": {"function": "plural marker", "category": "suffix"},
    "-li": {"function": "plural marker (variant)", "category": "suffix"},
    "-te": {"function": "copula/genitive", "category": "suffix"},
    "-se": {"function": "vocative/invocative", "category": "suffix"},
    "-ke": {"function": "nominalizer", "category": "suffix"},
    "-o": {"function": "genitive/possessive", "category": "suffix"},
    "-wi": {"function": "dative (for/to)", "category": "suffix"},
    "-ne": {"function": "locative (at/in)", "category": "suffix"},
    "-k": {"function": "possessive", "category": "suffix"},
    "-b": {"function": "agentive/copula", "category": "suffix"},
    "-s": {"function": "3rd person pronoun suffix", "category": "suffix"},

    # Prefixes
    "p-": {"function": "causative/verbal prefix", "category": "prefix"},
    "t-": {"function": "2nd person prefix", "category": "prefix"},
    "m-": {"function": "nominalizer prefix", "category": "prefix"},
}

# Sample inscriptions based on known REM entries
# Format: transliterated Meroitic text, with ':' as word separator in cursive
SAMPLE_INSCRIPTIONS = [
    {
        "id": "REM_0001",
        "site": "Meroe",
        "type": "funerary",
        "subtype": "offering_table",
        "text": "wos : mk : qore-l-o : Amnitenmomide : s : lh-se : ate-li : yi-s-li : pesto-b-ke",
        "description": "Offering table from Meroe royal cemetery",
        "period": "1st century CE",
    },
    {
        "id": "REM_0003",
        "site": "Meroe",
        "type": "funerary",
        "subtype": "offering_table",
        "text": "wos : mk : kdke-l-o : Amanitore : s : ate-li : yi-s-li : pesto-b-ke",
        "description": "Offering table of Queen Amanitore",
        "period": "1st century CE",
    },
    {
        "id": "REM_0068",
        "site": "Karanog",
        "type": "funerary",
        "subtype": "offering_table",
        "text": "wos : mk : Mtewidemni : lh-se : abr : mlo : ate-li : yi-s-li : pesto-b-ke",
        "description": "Funerary text from Karanog cemetery",
        "period": "2nd century CE",
    },
    {
        "id": "REM_0090",
        "site": "Karanog",
        "type": "funerary",
        "subtype": "stela",
        "text": "wos : mk : Yesbokemni : kdi : mlo : sr-se : ate-li : yi-s-li : pesto-b-ke",
        "description": "Stela of a woman from Karanog",
        "period": "2nd century CE",
    },
    {
        "id": "REM_0094",
        "site": "Karanog",
        "type": "funerary",
        "subtype": "offering_table",
        "text": "wos-i : mk-i-se : Aritene : abr : pelmos : lh : ate-li : yi-s-li : pesto-b-ke : mlo",
        "description": "Offering table of a pelmos (strategos)",
        "period": "2nd century CE",
    },
    {
        "id": "REM_0100",
        "site": "Faras",
        "type": "funerary",
        "subtype": "offering_table",
        "text": "wos : mk : Krmntene : kdi : sr-se : lh : ate : yi : pesto-b",
        "description": "Offering table from Faras",
        "period": "2nd-3rd century CE",
    },
    {
        "id": "REM_0141",
        "site": "Naga",
        "type": "royal",
        "subtype": "temple_inscription",
        "text": "qore-l : Natakamani : qo : mlo : apedmk : mk-se : selele : tenke : to : pesto-b-ke",
        "description": "Temple inscription of Natakamani at Naga",
        "period": "1st century CE",
    },
    {
        "id": "REM_0230",
        "site": "Musawwarat es-Sufra",
        "type": "religious",
        "subtype": "temple_graffito",
        "text": "apedmk : mk : qo-se : selele-wi : abr : mlo : beke",
        "description": "Graffito at Musawwarat temple of Apedemak",
        "period": "1st century BCE",
    },
    {
        "id": "REM_0310",
        "site": "Meroe",
        "type": "royal",
        "subtype": "enthronement",
        "text": "amni : mk : qore-l : Amanishakheto : kdke : qo : mlo : pesto-b : tenke : to : akine : to : selele",
        "description": "Enthronement text of Amanishakheto",
        "period": "1st century BCE",
    },
    {
        "id": "REM_0401",
        "site": "Meroe",
        "type": "royal",
        "subtype": "stela",
        "text": "qore-l-o : Tanyidamani : amni-te : qo : mlo-li : apedmk : mk : wos : mk : selele-wi : tenke : to",
        "description": "Royal stela of Tanyidamani",
        "period": "2nd century BCE",
    },
    {
        "id": "REM_0402",
        "site": "Jebel Barkal",
        "type": "royal",
        "subtype": "temple_inscription",
        "text": "amni : mk-se : qore-l : Tanyidamani : mlo : qo : beke-li : pesto-b-ke : to : selele",
        "description": "Temple inscription of Tanyidamani at Jebel Barkal",
        "period": "2nd century BCE",
    },
    {
        "id": "REM_0450",
        "site": "Qasr Ibrim",
        "type": "religious",
        "subtype": "votive",
        "text": "wos : mk : mhe-se : selele-wi : kdi : mlo : plote-b",
        "description": "Votive inscription at Qasr Ibrim",
        "period": "1st century CE",
    },
    {
        "id": "REM_0500",
        "site": "Meroe",
        "type": "funerary",
        "subtype": "offering_table",
        "text": "wos : mk : Mlewitenose : abr : pqr : lh-se : ate-li : yi-s-li : pesto-b-ke : mlo",
        "description": "Offering table of a pqr (deputy)",
        "period": "1st century CE",
    },
    {
        "id": "REM_0555",
        "site": "Sedeinga",
        "type": "funerary",
        "subtype": "stela",
        "text": "wos-i : mk-i : Tkhetemni : kdi : mlo : ate-li : yi-s-li : pesto-b-ke",
        "description": "Stela from Sedeinga necropolis",
        "period": "2nd-3rd century CE",
    },
    {
        "id": "REM_0600",
        "site": "Meroe",
        "type": "funerary",
        "subtype": "offering_table",
        "text": "wos : mk : Akinimnoteri : abr : arike : lh : ate-li : yi-s-li : pesto-b-ke : mlo",
        "description": "Offering table of a prince (arike)",
        "period": "1st century CE",
    },
    {
        "id": "REM_0620",
        "site": "Naga",
        "type": "religious",
        "subtype": "temple_inscription",
        "text": "apedmk : mk : qo : sebke : mk : amni : mk-se : selele-wi : qore-l : pesto-b-ke",
        "description": "Temple inscription at Naga, multiple deities",
        "period": "1st century CE",
    },
    {
        "id": "REM_0700",
        "site": "Meroe",
        "type": "royal",
        "subtype": "enthronement",
        "text": "qore-l-o : Amanikhabale : amni-te : mlo : qo : apedmk : mk-se : beke-li : tenke : to : selele",
        "description": "Enthronement text of Amanikhabale",
        "period": "1st century BCE",
    },
    {
        "id": "REM_0750",
        "site": "Musawwarat es-Sufra",
        "type": "religious",
        "subtype": "temple_graffito",
        "text": "apedmk : mk-se : qo : mlo : abr : selele-wi : beke",
        "description": "Graffito at the Great Enclosure",
        "period": "3rd century BCE",
    },
    {
        "id": "REM_0800",
        "site": "Meroe",
        "type": "funerary",
        "subtype": "offering_table",
        "text": "wos : mk : Beletense : kdi : kdke : lh-se : ate-li : yi : pesto-b",
        "description": "Offering table of a woman of kdke lineage",
        "period": "2nd century CE",
    },
    {
        "id": "REM_0850",
        "site": "Faras",
        "type": "funerary",
        "subtype": "offering_table",
        "text": "wos-i : mk-i-se : Krmtone : abr : beleqe : ate-li : yi-s-li : pesto-b-ke",
        "description": "Offering table of a chief (beleqe) from Faras",
        "period": "2nd-3rd century CE",
    },
    {
        "id": "REM_1001",
        "site": "Meroe",
        "type": "royal",
        "subtype": "stela",
        "text": "amni : mk : qore-l-o : Arnekhamani : qo : mlo : beke : apedmk : mk : selele-wi : to",
        "description": "Royal stela of Arnekhamani",
        "period": "3rd century BCE",
    },
    {
        "id": "REM_1010",
        "site": "Jebel Barkal",
        "type": "religious",
        "subtype": "temple_inscription",
        "text": "amni : mk : qo-se : wos : mk-se : mhe : mk-se : selele : pesto-b-ke : to",
        "description": "Multi-deity temple inscription at Jebel Barkal",
        "period": "3rd century BCE",
    },
    {
        "id": "REM_1050",
        "site": "Sedeinga",
        "type": "funerary",
        "subtype": "stela",
        "text": "wos : mk : Atritenose : abr : mlo : lh : sr-se : ate-li : yi-s-li : pesto-b-ke",
        "description": "Stela from Sedeinga",
        "period": "2nd century CE",
    },
    {
        "id": "REM_1100",
        "site": "Meroe",
        "type": "royal",
        "subtype": "enthronement",
        "text": "qore-l : Adikhalamani : amni-te : apedmk : mk-se : qo : mlo : tenke : to : akine : selele : pesto-b-ke",
        "description": "Enthronement inscription from Meroe",
        "period": "3rd century BCE",
    },
    {
        "id": "REM_1150",
        "site": "Qasr Ibrim",
        "type": "funerary",
        "subtype": "offering_table",
        "text": "wos : mk : Npatemeye : kdi : mlo : ate-li : yi-s-li : pesto-b-ke",
        "description": "Offering table from Qasr Ibrim",
        "period": "3rd century CE",
    },
    {
        "id": "REM_1200",
        "site": "Naga",
        "type": "religious",
        "subtype": "temple_inscription",
        "text": "apedmk : mk : qo : mlo-li : qore-l-o : Natakamani : kdke-l-o : Amanitore : selele-wi : pesto-b-ke",
        "description": "Joint royal inscription at Naga temple",
        "period": "1st century CE",
    },
]


# Nubian / Nilo-Saharan comparative vocabulary
# Based on Rilly 2007, 2010 "Le méroïtique et sa famille linguistique"
# and Bechhaus-Gerst 1989 "Nile-Nubian Reconsidered"
NUBIAN_COMPARATIVE = {
    # Old Nubian cognates (Rilly 2007, 2010)
    "to": {
        "meroitic_meaning": "land/territory",
        "old_nubian": "tou/to",
        "old_nubian_meaning": "land",
        "nobiin": "tó",
        "nobiin_meaning": "land",
        "dongolawi": "tuu",
        "confidence": 0.9,
    },
    "mk": {
        "meroitic_meaning": "god",
        "old_nubian": "masik/massig",
        "old_nubian_meaning": "god/lord",
        "nobiin": "masig",
        "nobiin_meaning": "god",
        "dongolawi": "",
        "confidence": 0.7,
    },
    "ate": {
        "meroitic_meaning": "bread/food offering",
        "old_nubian": "atte",
        "old_nubian_meaning": "bread",
        "nobiin": "atti",
        "nobiin_meaning": "bread",
        "dongolawi": "etti",
        "confidence": 0.85,
    },
    "yi": {
        "meroitic_meaning": "water/drink",
        "old_nubian": "yi/yii",
        "old_nubian_meaning": "water",
        "nobiin": "yii",
        "nobiin_meaning": "water",
        "dongolawi": "essi",
        "confidence": 0.9,
    },
    "qo": {
        "meroitic_meaning": "great/big",
        "old_nubian": "qor/gor",
        "old_nubian_meaning": "great",
        "nobiin": "goor",
        "nobiin_meaning": "big/great",
        "dongolawi": "guur",
        "confidence": 0.6,
    },
    "abr": {
        "meroitic_meaning": "man",
        "old_nubian": "auer",
        "old_nubian_meaning": "man/person",
        "nobiin": "uur",
        "nobiin_meaning": "man",
        "dongolawi": "",
        "confidence": 0.65,
    },
    "kdi": {
        "meroitic_meaning": "woman",
        "old_nubian": "kide/gide",
        "old_nubian_meaning": "girl/woman",
        "nobiin": "kede",
        "nobiin_meaning": "girl",
        "dongolawi": "kidi",
        "confidence": 0.75,
    },
    "lh": {
        "meroitic_meaning": "son/child",
        "old_nubian": "leh/lihi",
        "old_nubian_meaning": "child/offspring",
        "nobiin": "",
        "nobiin_meaning": "",
        "dongolawi": "",
        "confidence": 0.5,
    },
    "sr": {
        "meroitic_meaning": "sister/daughter",
        "old_nubian": "sur",
        "old_nubian_meaning": "sister",
        "nobiin": "suur",
        "nobiin_meaning": "sister",
        "dongolawi": "",
        "confidence": 0.7,
    },
    "mlo": {
        "meroitic_meaning": "good/beautiful",
        "old_nubian": "mel/mell",
        "old_nubian_meaning": "good",
        "nobiin": "meeli",
        "nobiin_meaning": "good",
        "dongolawi": "",
        "confidence": 0.6,
    },
    "tenke": {
        "meroitic_meaning": "west/western",
        "old_nubian": "tengi",
        "old_nubian_meaning": "west",
        "nobiin": "teengi",
        "nobiin_meaning": "west",
        "dongolawi": "",
        "confidence": 0.8,
    },
    "beke": {
        "meroitic_meaning": "to beget/produce",
        "old_nubian": "bek/big",
        "old_nubian_meaning": "to beget/give birth",
        "nobiin": "",
        "nobiin_meaning": "",
        "dongolawi": "",
        "confidence": 0.55,
    },
    "pesto": {
        "meroitic_meaning": "to give",
        "old_nubian": "per/pir",
        "old_nubian_meaning": "to give",
        "nobiin": "fir",
        "nobiin_meaning": "to give",
        "dongolawi": "per",
        "confidence": 0.5,
    },
    "selele": {
        "meroitic_meaning": "protection",
        "old_nubian": "selle",
        "old_nubian_meaning": "protection/mercy",
        "nobiin": "",
        "nobiin_meaning": "",
        "dongolawi": "",
        "confidence": 0.45,
    },
}

# Eastern Sudanic comparative data (broader Nilo-Saharan)
EASTERN_SUDANIC_COMPARATIVE = {
    "to": {
        "taman": "tu",
        "taman_meaning": "earth/land",
        "nara": "to",
        "nara_meaning": "ground",
    },
    "yi": {
        "taman": "yi",
        "taman_meaning": "water",
        "nara": "yo",
        "nara_meaning": "water",
    },
    "ate": {
        "taman": "",
        "taman_meaning": "",
        "nara": "aate",
        "nara_meaning": "food",
    },
    "kdi": {
        "taman": "",
        "taman_meaning": "",
        "nara": "kode",
        "nara_meaning": "woman",
    },
}
